<<<<<<< HEAD
title:              Clean Blog
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"
remote-theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
=======
title:              Blog_Cursos_3D
email:              loja3dgv@gmail.com
description:        Blog desenvolvido para Cursos 3D
author:             Liana Justo Petusk Filipe
baseurl:            "/Cursos_3D_Jekyll"
url:                "https://leppyt.github.io"

# Social Profiles
twitter_username:   
github_username:    LeppyT
facebook_username:  
instagram_username:  cursos3dbr
>>>>>>> c8513ae (jekyll build)
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
