title:              Blog Cursos 3D
email:              cursos3d.contato@gmail.com
description:        Aprenda um pouco mais sobre a Impressão 3D
author:             Cursos 3D e Loja 3D (Design por Liana)
baseurl:            "/Cursos_3D_Jekyll"
url:                "https://leppyt.github.io"
remote-theme: jekyll-theme-clean-blog
future: true
# Social Profiles
facebook_username:  
instagram_username:  cursos3dbr
youtube_username: Cursos3DBrasil
linkedin_username:

defaults:
  - scope:
      path: "/img"
    values:
      image: true

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
